---
- name: Copy SSH Key to Managed Nodes
  hosts: all
  become: yes
  
  tasks:
    - name: Copy SSH Key
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}" 
